### ISSUE TITLE
What error??

### ISSUE THREAD

**Issue by Bogdan015** [SamB440/MCRealistic#3]
**# What error??**

[09:54:55 WARN]: [MCRealistic] Task #16587 for MCRealistic v1 generated an exception java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R2/Packet at me.FCB.FCBMain$3.run(FCBMain.java:189) [?:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R2.Packet at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91] ... 8 more

**Comment by SamB440** [comment]
Hi there, what version of spigot and mcrealistic are you using?

**Comment by Bogdan015** [comment]
We have tried all versions and all the error

**Comment by SamB440** [comment]
It appears you are using 1.8. MCRealistic Reloaded does not currently support 1.8. You can find old MCRealistic versions here: http://dev.bukkit.org/bukkit-plugins/mcrealistic-realistic-minecraft/

**Comment by Bogdan015** [comment]
The old version does not support the Russian language

**Comment by Bogdan015** [comment]
Can somehow to edit the config was well very urgently need!

**Comment by SamB440** [comment]
Your only choice is to upgrade to 1.9 and use this version: https://www.spigotmc.org/resources/mcrealistic-reloaded.21628/download?version=88758 then.

**Comment by Bogdan015** [comment]
Our core can work with versions ranging from 1.7 finishing 1.9, but this version produces an error

**Comment by SamB440** [comment]
I'll send you a 1.7 version soon.

**Comment by Bogdan015** [comment]
I need to be able to change the language

**Comment by SamB440** [comment]
The version I will send you will have message configuration.

**Comment by Bogdan015** [comment]
Ок буду очень благодарен

**Comment by Bogdan015** [comment]
Ok I will be very grateful

**Comment by SamB440** [comment]
Hi there, I attempted to downgrade the plugin to 1.7, however many components used in 1.8/1.9/1.10 do not exist, therefor I cannot. I will try 1.8 with message configuration now, however.

**Comment by SamB440** [comment]
[http://forums.islandearth.net/spigotplugins/MCRealistic_1_8_R3.jar](url)

Try using that, beaware I have not tested it and it may not work!

**Comment by Bogdan015** [comment]
You can remove the blocks do not fall but the server gives an error

**Comment by SamB440** [comment]
I'm afraid your only choice is solid 1.9 upgrade, then.

**Comment by Bogdan015** [comment]
How to implement a system sleep, because not all servers can you sleep?
